sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - wget -O- http://neuro.debian.net/lists/trusty.de-md.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - gpg --keyserver ha.pool.sks-keyservers.net --recv-keys DD95CC430502E37EF840ACEEA5D32F012649A5A9
  - gpg --export DD95CC430502E37EF840ACEEA5D32F012649A5A9 | sudo tee /etc/apt/trusted.gpg.d/neurodebian.gpg
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends lynx fsl-5.0-core fsl-mni152-templates
script:
  - source /etc/fsl/fsl.sh; make tests
