sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - wget -O- http://neuro.debian.net/lists/trusty.de-md.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get update
  - sudo apt-get install lynx fsl-core
script:
  - source /etc/fsl/fsl.sh; make tests
